[package]
name = "proof_of_work_wasm"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
edition = "2021"
publish = false


[lib]
crate-type = ["cdylib"]
path = "proof_of_work.rs"
name = "proof_of_work"

[dependencies]
sha2 = "0.10.9"